JavaScriptAssignment/src/objects/Class__c.object
<CustomObject>
</CustomObject>

VFAssignment-1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestClasses/src/classes/ClassInformation.cls
/*
* Name: ClassInformation
* Description : This class is to retrieving information of students.
*/ 
public class ClassInformation {
    
    /*
    * Description: This function take classid as argument and returns all names of the 
    * students in that class as a list.
    */ 
    public static List<Student__C> getStudentsByClassId(String id)
    {
        List<Student__c> students = [Select name From Student__c where class__r.id = :id];
        return students;
    }
    
    /*
    * Description : This function returns a map where key is class and value is set of studentid in it.
    */ 
    public static Map<Id,List<Student__c>> getStudentIdsByClass(){
        
        Map<Id, List<student__C>> conMap = new Map<Id, List<student__C>>();
        for(class__c parent : [select id,(select id from students__r) From class__c]) {
            conMap.put(parent.Id, parent.students__r);
        }
        return conMap;
    }
    }