JavaScriptAssignment/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassTeacher__c</fullName>
        <label>ClassTeacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

VFAssignment-1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestClasses/src/classes/TestClassMyCountUpdate.cls
@isTest
public class TestClassMyCountUpdate {
    public static Class__c testClass;
    @testSetup
    public static void testSetup(){
        Contact testTeacher = new Contact(lastname='teacherLName',firstname='TeacherFname');
        insert testTeacher;
        
        testClass = new Class__C(name='testClass',ClassTeacher__c=testTeacher.Id,myCount__C=0);
        insert testClass;
        
    }
    @isTest
    public static void testTrigger_InsertNewStudent(){
        testClass = [Select name from class__c where name='testClass'];
        Student__C student = new Student__C(name='testStudent',LastName__C='studentLName3', sex__C='Female',Class__c = testClass.Id);
        // Perform test
        Test.startTest();
        insert(student);
        Test.stopTest();
        testClass = [Select myCount__c from class__c where name='testClass'];
        System.assertEquals(1, testClass.MyCount__c);
    }
    @isTest
    public static void testTrigger_DeleteStudent(){
        testClass = [Select name from class__c where name='testClass'];
        Student__C student = new Student__C(name='testStudent',LastName__C='studentLName3', sex__C='Female',Class__c = testClass.Id);
        insert student;
        // Perform test
        Test.startTest();
        delete(student);
        Test.stopTest();
        testClass = [Select myCount__c from class__c where name='testClass'];
        System.assertEquals(0, testClass.MyCount__c);
        
    }
    
    
}