JavaScriptAssignment/src/objects/Class__c.object
<CustomObject>
</CustomObject>

VFAssignment-1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Assignment-3/ApexAssignment/src/classes/ClassInformation.cls
public class ClassInformation {
    public static List<Student__C> getClassDetails(String id)
    {
        List<Student__c> students = [Select name From Student__c where class__r.id = :id];
        return students;
    }
    
    
    public static Map<Class__c,List<Student__c>> getListOfStudentId(){
        Map<Class__c,List<Student__c>> classMap;
      
        for(Class__c className: [SELECT Name,id FROM Class__c]){
            List<Student__c> students = [Select name From Student__c where class__r.id = :className.Id];
            classMap.put(className, students);
            
        }
        return classMap;
        
    }
    
    

}